version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: kittygram
      POSTGRES_USER: kitty
      POSTGRES_PASSWORD: kitty123
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    command: ./entrypoint.sh
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend
    volumes:
      - static:/app/build/
    expose:
      - 3000

  gateway:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static/
      - media:/media/

volumes:
  static:
  media:
  pg_data:
